### ISSUE TITLE
[1.16.5]Unexpected behaviour with steps in a redstone path

### ISSUE THREAD

**Issue by Rodg88** [stfwi/redstonepen#1]
Reposting this from the modpack tracker:
https://github.com/EnigmaticaModpacks/Enigmatica6/issues/4126

**Comment by stfwi** [comment]
Hi Rodg, ty for the hint, let me take a look in the E6 thread. Cheers,-

**Comment by stfwi** [comment]
(Fix as described in the E6 thread, fix version redstonepen-1.16.5-1.0.7). Cheers Rodg,-

**Comment by Rodg88** [comment]
Just tried the new version, and there is still some disconnection issue, but it seems easy to work around.

https://user-images.githubusercontent.com/2611674/151605469-29be704f-c1bf-474f-b897-2870da47f0df.mp4

Once the track is connected and working, it seems ok, and you can fix it by re-doing the top side segment.

**Comment by stfwi** [comment]
Uiui. Just saw the difference of your setup and the fix that I applied, and reproduced that. The bug happens only if the RS power source is off - at least in my dev environment. That smells like a change detection problem.

**Comment by stfwi** [comment]
Ahhh, it was simpler, I accidentally removed the update recursion while testing and did not add it again ("bug exchange" ....) This time I gonna upload the pre-jar here first - you make the impression of an excellent tester ;)

**Comment by stfwi** [comment]
Oky, I found yet another small thing and hope it's now all done and dusted. `redstonepen-1.16.5-1.0.8-b1` is the MC1.16 version, currently in approval on Curse. I'll close, and if we to find something, reopen. Cheers,-

**Comment by Rodg88** [comment]
Checked in-game, seems good now! Thanks!
