### ISSUE TITLE
Shift-clicking items into the Redstone Logic Control GUI locks the game

### ISSUE THREAD

**Issue by Serifina** [stfwi/redstonepen#11]
Discovered that if you shift-click items into the Redstone Logic Control GUI, the game locks and just stalls as is. Found this out with my modpack, but I tested this in a fresh instance with just this mod in it, and confirmed it's still happening.
[latest.log](https://github.com/stfwi/redstonepen/files/8828950/latest.log)

This is the log, but no errors seem to appear. It just... freezes.

**Comment by stfwi** [comment]
Hi serfina, ty for the hint, I could reproduce and fix the issue - pushed to Curse (`redstonepen-1.18.2-1.0.10`). Cheers,-
