### ISSUE TITLE
Any chance to get fabric support?

### ISSUE THREAD

**Issue by TheCherry** [stfwi/redstonepen#12]
Any chance to get fabric support?

**Comment by stfwi** [comment]
Hi, before I answer let me take a look at Fabric ;)

**Comment by TheCherry** [comment]
Many mods use a kind of "multi compile" thing. But I am not so familiar with minecraft modding.
See maybe a example here? https://github.com/jaredlll08/Clumps

**Comment by stfwi** [comment]
Thanks for checking this out. The main work will likely be the compatibility of the java code, and how I can project the library I have already for Forge to Fabric. Some things seem easy to port, others (like registries, block/item overrides, Forge-events, config, rendering, etc) are quite differently handled. I'll experiment a bit what is possible and where the problems are located ;)

**Comment by stfwi** [comment]
Oky, I managed to compile and very briefly test a first 1.19 Fabric version for the mod, do you like to assist with testing? ;)
[redstonepen-1.19-fabric-1.0.11.zip](https://github.com/stfwi/redstonepen/files/9033796/redstonepen-1.19-fabric-1.0.11.zip)

**Comment by stfwi** [comment]
Quick correction, I forgot something that causes a server crash in the initial build above. Correction is here ...
[redstonepen-1.19-fabric-1.0.11.zip](https://github.com/stfwi/redstonepen/files/9034414/redstonepen-1.19-fabric-1.0.11.zip)

**Comment by stfwi** [comment]
Okay, the initial beta build is on Curse.
