### ISSUE TITLE
Crashes on current latest Forge versions (>=41.0.64)

### ISSUE THREAD

**Issue by Sollisnexus** [stfwi/redstonepen#13]
I'm using Aternos to host my minecraft server for a local discord server and the latest Forge update put Redstone Pen outta commision at this time. Here's part of the log I get when it crashes.
![Screenshot 2022-07-08 154618](https://user-images.githubusercontent.com/44639933/178060403-be45effd-6c15-4dbb-945f-78b329c1a61a.png)

**Comment by stfwi** [comment]
Hi, ty for the hint. There are some changes in the Forge ongoing. The Smiths do some clean-ups and migrations fitting to the new MC version, as long as not many mods are on 1.19.  So we need to given them that time. I'll check what I can already update or fix ;). Cheers,-

**Comment by stfwi** [comment]
Hi again - I have pushed [redstonepen-1.19-forge-1.0.13](https://www.curseforge.com/minecraft/mc-mods/redstone-pen/files/3870738) with a Forge update. I hope that does it for this MC version ;) Cheers,-

**Comment by rootwalla** [comment]
Nope, gonna need another update post forge .94 (they changed something, again).

**Comment by stfwi** [comment]
Oky, pushed it to Forge 41.1.0, it's already on Curse, can you give it a try? Cheers,-
