### ISSUE TITLE
Request: Hold right click and drag to get a perfect line

### ISSUE THREAD

**Issue by TheDeviantCrafter** [stfwi/redstonepen#14]
Current behavior: Drawing a line requires clicking a fairly small hitbox. Long lines require fairly careful aim to avoid accidentally leaving gaps or placing redstone lines going sideways.

Proposed behavior: Holding right click and dragging the pen across multiple blocks would draw a perfect line connecting them.

**Comment by stfwi** [comment]
Hi, I need to think about it and maybe experiment a bit. I only get click/use events from the API, but no mousedown/mouseup, except when explicitly hooking into the client side. Most of the people asked so far were also happy with the placement method of the mod. I definitely take the point to consider this. Cheers,-

**Comment by stfwi** [comment]
Okay, so all things in sight considered, it's technically not easy to maintain, and the far most uses for the pen I have seen so far are situations where you want to control exactly the wiring directions in tight space. I think I gonna skip this one. Nonetheless, thanks for the input Deviant. Cheers,-
