### ISSUE TITLE
[Bug] Block signal connectors don't work

### ISSUE THREAD

**Issue by Grumpey102** [stfwi/redstonepen#16]
Hey,

I'm using Fabric API 0.58.0+1.19 and Redstone Pen 1.0.11 for Minecraft 1.19. I removed all the other mods to make sure it's not just some kind of incompatibility.

I'm trying to use the redstone pen as intended but the Block signal connector (the dot in the middle) doesn't seem to work.

![22-08-05 - javaw - 13-06-39](https://user-images.githubusercontent.com/110056966/183066935-3acaa94c-6003-4323-86a0-7dd0bd1c0093.gif)

I'm not sure if the above gif gets loaded (I don't see it in the preview), so if it isn't, here is the gif uploaded somewhere else:
https://i.imgur.com/WA95qBh.gif

Cheers,
Grumpey

**Comment by stfwi** [comment]
Hi Grumpey, thanks for the hint - seems I forgot to implement the body of a function when porting from Forge ;). 
It's push to Curse (`redstonepen-1.19-fabric-1.0.16.jar` and `redstonepen-1.19.1-fabric-1.0.16.jar`) and should be approved soon.
Cheers, wile
