### ISSUE TITLE
The number of uses of the function is too small

### ISSUE THREAD

**Issue by Hakoyu** [stfwi/redstonepen#18]
I hope to increase the number of times the function is used or remove the limit, otherwise complex programs are not easy to write

![image](https://user-images.githubusercontent.com/48956359/184544564-30db732b-7325-449d-9cb3-d445b2dc9b4e.png)

**Comment by Hakoyu** [comment]
In the above diagram, the program needs to send pulses to multiple ports in sequence
But because of the function limitation, it can only send four times

**Comment by stfwi** [comment]
Hi, oh, I did not except that so many timers would be needed.  Let me think about it - on the one hand I like to have limitations for the block (so that there is a challenge in game), but I can also understand that each direction should have a timer instance available.

**Comment by Hakoyu** [comment]
Thank you for your reply
Although it is possible to use multiple RLCs to control, it makes it more difficult to write
Or you can get an upgraded RLC that is more difficult to make to solve this problem
This will make it more difficult

**Comment by stfwi** [comment]
So, in the recent releases I added the TIVx pulse gen, and timer instances were increased. Should be good now for the use cases of the block. Cheers,-
