### ISSUE TITLE
RLC visual glitch causes programming confusion

### ISSUE THREAD

**Issue by aurumvorax** [stfwi/redstonepen#20]
Ver 1.08, but likely present in all future versions

When you place a RLC on the ceiling, the visual colours do not match the logical colours for the IO.  2 colours get swapped.  Likely just a visual glitch caused by flipping the texture for use upside down, but it causes confusion with programming.

To replicate: put a RLC upside down on a ceiling, run a bit of redstone out of each side with the pen.  Use the RLC to output on each of the IO ports, and see what lines up and what doesn't.

**Comment by stfwi** [comment]
Hi aurum, aye I have seen the issue a short time before and have actually fixed it in `v1.2.17`. Just didn't get around to port the fix all the way down to 1.16. Hope that I get to tackle that in the next week or so. It's (as you already reckoned) a swapped model.
Cheers,-

**Comment by aurumvorax** [comment]
Excellent.  It's not a big deal once you know about it, just figured I'd let you know.  That is definitely the kind of bug that is hard to catch in QA :)

**Comment by stfwi** [comment]
Hi again, just wanted to start porting down the fix and had to realize that I was waffling bollox - the fix for 1.16 is already pushed:
`v1.16.5-1.0.9 ` (https://www.curseforge.com/minecraft/mc-mods/redstone-pen/files/3983482). Sorry about the pointless delay there ;/.
