### ISSUE TITLE
Redstone Text Panel

### ISSUE THREAD

**Issue by rabrunos** [stfwi/redstonepen#21]
Hello again!
After so long, today I had an idea and I wanted to share it with you!

### "LCD" Panel

Today I downloaded an Elevator mod called "Modern Elevators and Escalators"
And it has an item called "Elevator Display Panel". This item displays the configuration texts.

  So I thought, it would be nice to have a Redstone LCD Panel that did something similar.
  
Redstone sends 16 signals (0-15).
With that in mind, the panel would be configured using the signals.
There would be 16 text fields, each 1 for a signal.
Or it could be configured in a similar way to the Redstone Logic Controller of the Redstone Pen.

So, on receiving 1 signal, it would display text 1, but on receiving 2 signal, it would display text 2.

It would be nice if it had at least one panel that would display a text if it's on and not display if it's off (in case 16 text fields were too many, but I still prefer 16 hahaha)

**Comment by stfwi** [comment]
Hi, ty for the input man. Let me deeply think about this - the pen mod is essentially about redstone tracks and a bit of vanilla-like signal repeating (-the RLC is admittedly a bit more complex-). I didn't have levers/buttons/displays in mind as other mods cover this already very well, and we try to combine mods for the fun of it. 

Let me double check first for collisions with the other mods - Danny's stuff (Tiny RS and addons), McJty's tools, Jukaar (supplementaries) has definitely a crystal display, Lothazar (cyclic) had a display already in 1.12, but I can't remember if these allow changing custom text ...

**Comment by faelBrunnoS** [comment]
Thanks for listening!

I made the Features request here, but I was torn between resquesting here or ordering from Gauges and Switches!
In my mind, I had some ideas on how to use the panel!

For example: Show if the system is ON by just putting ON/OFF on channels other than LCD or show which system is currently working in case of multiple connected systems.  And a few others too and of course several others that I haven't thought of but creative builders will!

**Comment by stfwi** [comment]
Quick notifier, a simple gauge block is now integrated into the mod - which is the closest to this request. Elaborated panels have become too far from where the mod is evolving. So I'll close this one. Cheer's,-
