### ISSUE TITLE
Black screen

### ISSUE THREAD

**Issue by wisquimas** [stfwi/redstonepen#26]
I see black screen when i put an item of this mod in my hand.
I use Optifine I9, Minecraft 1.19.2

**Comment by stfwi** [comment]
Hi, I suspect optifine hooks into the overlay rendering in a problematic way. As a context, I use the standard Minecraft rendering methods for showing the blockstate. 

Track the issue down, which mode version do you have, and are you on fabric or forge?

Cheers,-

**Comment by stfwi** [comment]
Oky, [redstonepen-1.19.2-forge-1.2.20.jar](https://www.curseforge.com/minecraft/mc-mods/redstone-pen/files/4393700) is in approval. Optifine seems to be the friend of all modders due to the brilliant compatibility ;).
