### ISSUE TITLE
Pistons not working

### ISSUE THREAD

**Issue by Fluppkin** [stfwi/redstonepen#28]
Every time i join the server the pistons stop working with signals from red-stone pen circuit lines. i have to put a separate block in the place of pistons every time and have to make a block update at that position then again place the piston in that place to make it work. its really really problematic.

**Comment by stfwi** [comment]
Hi, oky, can you give me the version of the mod/minecraft, and if it's forge or fabric (best the complete JAR file name) for reproduction? Should not be a big issue. Cheer's;;

**Comment by stfwi** [comment]
Yepp, saw it in 1.20.1/1.20.2, fix versions are `redstonepen-1.20.1-neoforge-1.3.22.jar` and `redstonepen-1.20.2-fabric-1.6.24.jar`.
