### ISSUE TITLE
[CRASH] crash 1.20.1

### ISSUE THREAD

**Issue by lostopkk** [stfwi/redstonepen#29]
https://mclo.gs/d31QUSb

**Comment by stfwi** [comment]
Hi, the mod version installed on your machine is for 1.20.2, the log shows MC 1.20.1. So, the changes [in the commit here](https://github.com/stfwi/redstonepen/commit/b073a321f5b6bd6d2e8ef0480090577d3bedc5f5#diff-211276cc3088e173d3a0b70e2ec1afa374b81706d193ed379b436f89e313202e) for the Minecraft version port cause the issue.

The latest versions for 1.20.1 are here
- https://legacy.curseforge.com/minecraft/mc-mods/redstone-pen/files/4745120
- https://modrinth.com/mod/redstonepen/version/1.5.23

May I ask: Did you use mod manager, and the 1.20.2 version was automatically installed, or manual?

Cheer's

**Comment by lostopkk** [comment]
> Hi, the mod version installed on your machine is for 1.20.2, the log shows MC 1.20.1. So, the changes [in the commit here](https://github.com/stfwi/redstonepen/commit/b073a321f5b6bd6d2e8ef0480090577d3bedc5f5#diff-211276cc3088e173d3a0b70e2ec1afa374b81706d193ed379b436f89e313202e) for the Minecraft version port cause the issue.
> 
> The latest versions for 1.20.1 are here
> 
> * https://legacy.curseforge.com/minecraft/mc-mods/redstone-pen/files/4745120
> * https://modrinth.com/mod/redstonepen/version/1.5.23
> 
> May I ask: Did you use mod manager, and the 1.20.2 version was automatically installed, or manual?
> 
> Cheer's

manual

**Comment by stfwi** [comment]
oky, I presume it's resolved then ;) If something shows up, re-open it. Cheer's
