### ISSUE TITLE
This mod makes lan not games not work

### ISSUE THREAD

**Issue by nickademas** [stfwi/redstonepen#30]
trying to join a lan world with this mod gives "io.netty.handler.codec.DecoderException: java.lang.IllegalArgumentException: Unknown recipe serializer minecraft:nether_wart_block" and makes joining lan worlds impossible 

Minecraft 1.20.4
Fabric loader 0.15.1
Fabric api 0.91.2+1.20.4
Redstone pen 1.8.25

**Comment by stfwi** [comment]
Hi, ty for the hint let me take a look what's going on there. Recipe serializer `nether_wart_block` sounds very strange ;)

**Comment by stfwi** [comment]
Oky, was reproducible and could be fixed. The file is in approval on Curse, the file on Modrinth is already up: `https://modrinth.com/mod/redstonepen/version/1.8.26`. Cheer's;
