### ISSUE TITLE
Trailing comma in mcmeta throws a million errors in game log

### ISSUE THREAD

**Issue by TropheusJ** [stfwi/redstonepen#33]
The mod's mcmeta file has a trailing comma in it that makes it fail to parse.
```
[01:14:08] [main/ERROR] (ResourceLoader) Couldn't load filter metadata from pack "Redstone Pen":
com.google.gson.JsonParseException: com.google.gson.stream.MalformedJsonException: Expected name at line 5 column 4 path $.pack.pack_format
```
Manually removing this trailing comma fixes all errors.

**Comment by stfwi** [comment]
Hi J, thanks for the hint, gonna take a look at the weekend. Which MC version (forge/fabric) are you on? Cheer's;-

**Comment by stfwi** [comment]
Ok, saw one in 1.20.x-fabric mainline and pushed a fix. But I do not get any errors with mc-1.20.4, fabric-0.91.2+1.20.4, redstonepen v1.20.4-1.8.28 when testing. Forge/neoforge 1.20.1 have no trailing comma. So, still need your version to double check, could you drop it in here?. Ty, Cheer's;-

**Comment by TropheusJ** [comment]
Using 1.5.24 on 1.20.1 currently, with Quilted Fabric API 7.2.2+0.88.1-1.20.1. Might be a quirk of the quilt resource loader.

**Comment by stfwi** [comment]
Oky v1.8.28 is up on curse and modrinth, comma is removed with that release. Ty again for the hint man! Cheer's
