### ISSUE TITLE
pen-made wiring inconsistent with dispener if connected on top of dispenser(using centre-connect)

### ISSUE THREAD

**Issue by Shinchai** [stfwi/redstonepen#34]
Connecting a button to a dispenser by top connection (shown below) activates a dispenser once but no more (the circuit must be reconnected by breaking a part and putting it back again to make it work again)
![2024-02-15_06 02 57](https://github.com/stfwi/redstonepen/assets/19682190/1de01daa-e22e-4fd4-9c3f-1d7ff06c1031)

however, using the pen to power a block on top of the dispenser works fine.

![2024-02-15_06 01 36](https://github.com/stfwi/redstonepen/assets/19682190/7b728466-3195-42dd-820a-15fe3ea837fd)

**Comment by stfwi** [comment]
Hi Shinchai, thanks for reporting this. Which mod file are you using (or mod version, minecraft version, [neo]forge/fabric)? Cheers;

**Comment by stfwi** [comment]
Hi, mod version 1.20.2-1.6.28 is pushed on Curse and Modrinth, this should fix the issue, I could not reproduce it after pulling in the fixed from 1.20.4.

Could you risk a glimpse and tell me if it's okay on your machine, too? Then I can mark the version as release. Cheer's!

**Comment by Shinchai** [comment]
I'm using mod version 1.8.28 for minecraft 1.20.4 with fabric loader 0.96.1. Also I am only using two redstone related mods only, this one & redstone bits (though i do have the full set of optimization mods given by adrenaline, might be that is interfering?)

Sometimes in my other redstone circuits, I have to re-make a circuit by destroying one block and putting it back to make the circuit work normally (otherwise, similar result happens, only triggers once or never at all)

Im using these mods if it helps: (red dashed ones are installed after this incident so not relevant)
![image](https://github.com/stfwi/redstonepen/assets/19682190/8a1aa48f-688a-4069-91e6-429632c10b12)

**Comment by stfwi** [comment]
Hi, ty for the listing and the details. My impression is it's gonna be a tricky one ;). Let's see what a run in the IDE may reveal.

**Comment by stfwi** [comment]
Ya, it's definitely a thing to reproduce that. Still did not find what's happening there.

**Comment by stfwi** [comment]
Okay, was reproducible and could be fixed in one go with doing some performance optimizations. No other mod was involved in the bug, this was a change in Minecraft that I did not see before.
Uploaded version `v1.20.4-1.8.29` to modrintrh and curse:

- https://modrinth.com/mod/redstonepen/version/1.8.29

Can you give it a try and write a short feedback if that solved the issue also in your setup? Cheer's;-

**Comment by Shinchai** [comment]
I remade the setup shown in the pic and it works fine now. Thanks for the update!

**Comment by stfwi** [comment]
Perfect that, thanks for the quick feedback;;
