### ISSUE TITLE
Issue #32 on 1.20.2-1.6.24

### ISSUE THREAD

**Issue by oknacupZero** [stfwi/redstonepen#35]
I was able to recreate #32 on .2 version

https://cdn.discordapp.com/attachments/1207681189033414696/1207682849084542976/2024-02-15_20-37-39.mp4?ex=65e0894c&is=65ce144c&hm=39f644c6e6e75eeaa9588a3e326caa654db1a840981b91a53cc865cf4a116ebe&

**Comment by stfwi** [comment]
Hi, thanks for the feedback. The fix is in mod version 1.6.27, which is not back ported to 1.20.2 (only 1.20.1 and 1.20.4). Have to admit I did not decided yet to do the back-port, as people quickly updated to 1.20.4 and the issue is minor.

**Comment by stfwi** [comment]
Ok, crash report for 1.20.2 dropped in. I am trying to fix this in one go.

**Comment by stfwi** [comment]
Hi oknacup, I pushed version 1.20.2-1.6.28 to Curse and Modrinth as beta version, could to take a look and tell if the problem is fixed (for re-tagging as release version)? Chereo, wilE.

**Comment by oknacupZero** [comment]
Looks like this have been fixed.

**Comment by stfwi** [comment]
Oky, thanks for the feedback, I close the issue then; Cheers, wile;
