### ISSUE TITLE
Issue #30 on 1.20.2-1.6.24

### ISSUE THREAD

**Issue by oknacupZero** [stfwi/redstonepen#36]
"Internal Exception: `io.netty.handler.codec.DecoderException:` `java.lang.IllegalArgumentException:` Unknown recipe serializer minecraft:nether_wart_block"
Happened on joining dedicated server.

**Comment by stfwi** [comment]
Hi, let me take a look at this, this looks like 1.20.1 build config used in 1.20.2. It also gives me a reason to make a back-port fix for the previous issue ;) Cheers;

**Comment by stfwi** [comment]
Hi, same for this issue, could you take a look if the issue is also resolved in your setup? Cheers;

**Comment by oknacupZero** [comment]
Can join with no issues.

**Comment by nuypham** [comment]
Nice! Thank you, Also Fixed issue Internal Exception recipe from Croptopia mod when joining the server.

**Comment by stfwi** [comment]
Oky very nice, thanks for the feedback; Cheers,-
