### ISSUE TITLE
Control Panels

### ISSUE THREAD

**Issue by VadimP22** [stfwi/redstonepen#39]
A long time ago (minecraft 1.7.10) I really liked the **Project Blue** mod (https://www.csse.canterbury.ac.nz/greg.ewing/minecraft/mods/ProjectBlue/). This mod is an addon for Project Red that adds awesome control panels. It makes it possible to place up to 16 redstone devices (levers, buttons, lights) on a 4x4 grid on single block. These controls can also be signed with charcoal.

I found these panels very useful as they replace a whole wall of levers, buttons and lights.

Screenshot
![Screenshot](https://www.csse.canterbury.ac.nz/greg.ewing/minecraft/mods/ProjectBlue/doc/SecretBaseControls75.png)

**Comment by stfwi** [comment]
Hey vadim, yee I remember that panel ;). Have to admit I liked that, too, but also would like to keep the Redstone Pen mod in a very vanillarish look. So there are no plans at the moment to add text based visual features. Let's leave the issue open that it stays on the radar. Cheer's,-

**Comment by stfwi** [comment]
Oky, from some design decisions, I'll close this one, elaborated visualizations are covered in various other mods, and the Pen is intended to stay focussed on its core functionality. Cheers,-
