### ISSUE TITLE
[Suggestion] Please make a Discord (or invite me :D)

### ISSUE THREAD

**Issue by Aerotactics** [stfwi/redstonepen#45]
I found this mod by accident and it is the perfect Redstone upgrade. I'm a programmer, so I think in code better than Redstone, but I do like Redstone. I want to share builds and code with others who are enjoying this mod, and maybe get help with understanding, so I suggest expanding the community and creating a Discord or Revolt server.

If you dont, I can create one and leave an invite. This minecraft community is going to grow among programmers and scripters, and we need a place to share ideas.

**Comment by stfwi** [comment]
Hi man, aye, I agree Discord is a really nice platform for that, and the idea for opening a server (at that time "for all my mods") was a vivid option in discussion. Trouble was and still is: I simply have to honestly admit that I don't have the time to appropriately maintain and moderate such a server - would be irresponsible to open one then.


Hence, I'm really happy you directly added a proposal - would be a cool thing indeed. If you like to open a server, I can link it in the mod description pages and here on the Hub.


As recommendation (just for brainstorming), I would extended the perimeter a bit and name it something like "Modded Redstone Community" or similar. That would open up to you addressing and linking topics of multiple redstone mods (or cool redstone features of mods). In a first server search, I did not see anything like this yet (only common redstone or very mod specific servers).


As example, when being asked about good mods or feature requests for my mods,  I frequently reference or recommend mods like:
- McJtys tools (RF tools)
- Danny's stuff (Tiny redstone)
- Commoble's wires and gates (More Red)
- Project Red (tjp & team)
- Computer Craft and extension mods.
- Gauges and Switches (by me until 1.19.4, successor already available by the community - thankfully)
- Wifi Redstone (cbe)
- Curcuit Maker (amadornes)
- Redstone Paste (for 1.12, Redstone Pen is in a way the follow-up of that)
- Logic Gates (can't remember the author now ;) )
- (Depending on the pack also Immersive Engineering circuits etc).

So, the community is already big, and what the various mod devs already cover is beyond the feature set of Redstone Pen. I personally like to have quite a few RS mods in packs, and combine them ;)

**Comment by Aerotactics** [comment]
I havent used those other mods, but I agree there is a need for a community. I also understand not having the time to manage it yourself. I'll get back to you soon, thanks for the insight into the wider community!

**Comment by Aerotactics** [comment]
I have created the Discord server. This link will remain active: https://discord.gg/6K958GsWq5
Here's a preview of the Disboard description: ![image](https://github.com/user-attachments/assets/dba05185-15fb-4aff-98a9-7acddaeb3884)

**Comment by stfwi** [comment]
Looks very nice. I just joined to the server. Shall I directly link it on the mod sites?

**Comment by Aerotactics** [comment]
Yes, you may use that same link is a permanent invite :D

**Comment by stfwi** [comment]
Oky, it's referenced on Curse, Modrinth and here in the readmd. Ty again for doing this. Cheer's;-
