### ISSUE TITLE
RLC preview FOV doesn't match game FOV

### ISSUE THREAD

**Issue by MeowcaTheoRange** [stfwi/redstonepen#48]
While holding the RLC, the item shows a preview of what orientation and position it will be in when it is placed.
However, when your FOV is set to anything lower or higher than 70°, you may notice the preview's FOV is different, causing this weird "double-vision" effect where the item appears out of line with the grid and bigger/smaller than it would on 70°.

## Screenshots (Fabric 1.19.4, Java 17):

The RLC, seen at 30° FOV:
![2024-07-20_17 13 57](https://github.com/user-attachments/assets/66587c3e-327c-4bf1-a212-2e2bc9d16764)

The RLC, seen at 70° FOV (*Normal*):
![2024-07-20_17 18 38](https://github.com/user-attachments/assets/651b295b-f2a5-4f2f-a297-20746c2c8b58)

The RLC, seen at 110° FOV (*Quake Pro*):
![2024-07-20_17 14 18](https://github.com/user-attachments/assets/6c2a8882-b2eb-4674-be34-d70a629dc142)

This also happens when the item is viewed through a Spyglass, like when using it in the offhand before hovering over a block space in reach.

The RLC, viewed though a Spyglass on 70° FOV:
![2024-07-20_17 20 57](https://github.com/user-attachments/assets/5075aea9-c897-4617-8b5e-28b95667b0d1)

The RLC, zoomed into with Zume on 70° FOV:
![2024-07-20_17 23 24](https://github.com/user-attachments/assets/3bd4e9c7-e808-490b-811d-4eb261e32341)

**Comment by stfwi** [comment]
Hi, ty for the hint and the details. I checked with latest 1.21 fabric version, too - same issue; I simply did not take FOV into account. Currently no real idea yet how to fix it, maybe just hooking into another rendering step. Let's see ;)

**Comment by stfwi** [comment]
... subscribing to the correct level renderer helped ;). 1.21 Scheduled for the next release.

**Comment by stfwi** [comment]
Oky, fixed in v1.11.36.
