### ISSUE TITLE
Feature request - (Or new mod?)

### ISSUE THREAD

**Issue by instinxx** [stfwi/redstonepen#49]
Can you make a version that places gunpowder? Would be useful for dramatic TNT fuses, lighting things on fire etc. Potentially even a type of permanent gunpowder as an option as well?

**Comment by stfwi** [comment]
Hi, would be a new mod indeed. Have to admit this is quite far off from what my mods are covering. Please browse a bit in Curse and Modrinth, I remember to have seen a mod has covers gunpowder tracks with Flint&Steel ignition already, this sounds like what you are looking for. Cheers,-
