### ISSUE TITLE
[Feature Request] Compatibility with Moving Elevators

### ISSUE THREAD

**Issue by faelBrunnoS** [stfwi/redstonepen#5]
Is there anything that can be done to fix this?

https://github.com/SuperMartijn642/MovingElevators/issues/98

**Comment by stfwi** [comment]
Hi man, the track unfortunately needs a block entity to work. IIRC a Relay is just a block and could go outside the elevator so that is it not seen in the cabin. Have to honestly admit I have no idea if that will work with moving blocks however - can you give me feedback in case it crashes ;)?

**Comment by faelBrunnoS** [comment]
I tried it here, but unfortunately the Elevator mod limits us a lot because of its mechanics.
I ended up giving up.

**Comment by stfwi** [comment]
Aye, Minecraft makes moving parts very hard to handle for mods - no blame attaches, Mojang implements what they need, and Martin tries to make the best out of it in the elevator mod, but there are limitations what mods can do there :/. Maybe moving parts have other opportunities in future MC versions.

**Comment by faelBrunnoS** [comment]
Yes, I even tried using another elevator mod, but Martin's mod is irreplaceable, at least for me!
So I'll look for other ways to do this!
