### ISSUE TITLE
TIV doesn't execute if Ticks (T) is less than 3

### ISSUE THREAD

**Issue by Aerotactics** [stfwi/redstonepen#50]
I'm trying to make a tick counter for a timing thing, but discovered TIV doesnt work when T is less than 3. If we could detect TIV every frame, we could have a reliable tick counter

**Comment by stfwi** [comment]
Quickly double checked, it's compensating for the Redstone tick quantization (1 redstone tick 2 game ticks). So, I think this has to be documented. As we discussed in the DC (FTR for others stumbling over that), tick counting can be done e.g. like:

```
T0 = IF(Y.RE, CLOCK(), T0)
DT = IF(Y.FE, CLOCK()-T0, DT)
```

**Comment by stfwi** [comment]
In-Game documentation will be rolled out with the next release ;)

**Comment by stfwi** [comment]
Alright, fix version `v1.11.36` is up on the distribution platforms. Cheer's;-
