### ISSUE TITLE
It's possible for a wire to break signal

### ISSUE THREAD

**Issue by Aerotactics** [stfwi/redstonepen#51]
I think this bug occurs if you place a wire line, break a block in the middle, then replace the wire. The signal doesn't connect up properly. I'll do some testing in the meantime.

EDIT: Steps to reproduce
1) Have power enter a block from 1 edge
2) Place a wire interior to the adjacent block, that is not powered by the signal
3) Place a wire connected to the signal
4) The signal no longer passes through the wire as expected

For the infinite signal:
1) Have power enter a block from 1 edge
2) Place a wire connecting to that signal
3) Place a wire interior to the previous wire that is not connected to the wire
4) Remove the power input. The wire will remain powered

![gif87](https://github.com/user-attachments/assets/2ca7f57f-b96f-48d5-8e13-94cb8011a3e0)

**Comment by Aerotactics** [comment]
![image](https://github.com/user-attachments/assets/08f0b51d-1250-4727-a85d-8eed1172c12d)

**Comment by Aerotactics** [comment]
It seems that if you have multiple wires in the same block space, the signal gets confused
![image](https://github.com/user-attachments/assets/c22eb1f3-d577-4423-abac-a1a184f2656b)

**Comment by Aerotactics** [comment]
Another anomaly 
![image](https://github.com/user-attachments/assets/a00f245e-54b4-4ee3-81ea-30eed0362095)

**Comment by stfwi** [comment]
Hey man, ty for the report. The complicated fixes that had to be made with the new update order has apparently introduced a regression that slipped the checks ;; That's gonna be a "Vanilla Redstone one" - aka a horrible one to fix ;). I presume the neighbour updates of the track networks interfere now.

**Comment by stfwi** [comment]
... It is likely that late 1.20.x (neo:forge + fabric) may be affected as well, this was a vanilla change.

**Comment by Aerotactics** [comment]
Yeah. Easy to work around for now, just less compact wiring

**Comment by stfwi** [comment]
For 1.21 fabric I just pushed a beta for testing. It was a regression issue when working around changed redstone handling in vanilla and mods. Could you risk a glimpse at that? I was not able to test it in depth (like what happens to Dropper triggering from various sides, or e.g. Alternate Current and similar mods go along with it) - so "maybe fxed" ;).

Download link is: https://modrinth.com/mod/redstonepen/version/1.11.36

**Comment by stfwi** [comment]
Oky the actual fix is out. There is still the visual glitch when placing, I could not track that - the debug info show that the block knows the correct values, so this looks as having something to do with the network synchronization - which is very strange.

For the next while we'll have to live with it, I have to defer the task for timing reasons.

**Comment by stfwi** [comment]
Fixes are up on the distribution platforms. The visual glitch is considered in a separate thread/issue.
