### ISSUE TITLE
RLC code should stay on the RLC if it is broken and picked up.

### ISSUE THREAD

**Issue by Aerotactics** [stfwi/redstonepen#55]
It should work like NBT data, where if you pick up the item, the code remains on it instead of getting cleared. This will save many headaches.

**Comment by stfwi** [comment]
Hi, can you double check in survival mode? In creative there is no event to pop off the blocks, it's directly removed, and the mod code bypassed. In survival, it should retain the code, and when placed again, the RLC should be in PAUSE mode.

**Comment by stfwi** [comment]
Let's close this, works in survival mode.
