### ISSUE TITLE
Block placement preview supports vanilla blocks

### ISSUE THREAD

**Issue by specialTT** [stfwi/redstonepen#57]
The items in this mod have placement hints, so whether to add such a function to the vanilla redstone blocks, and the hints can be turned off.
I know that vanilla redstone blocks do not need to have such a function, so is it possible to also allow vanilla redstone blocks to be placed on the side of the block? Except redstone dust.

**Comment by stfwi** [comment]
Hi TT, I am afraid modifying the vanilla Redstone-triggered blocks will result in various incompatibilities, especially with other mods modifying the functionality of such blocks (e.g. Quarks as one example). So the risk of breaking the game for players vs. the enhanced placement is likely a problematic trait-off. But thank you for the input and sharing the ideas! Cheer's;;
