### ISSUE TITLE
[Feature Request] Wireless Redstone

### ISSUE THREAD

**Issue by faelBrunnoS** [stfwi/redstonepen#6]
### Wireless Transmitter and Receiver

- Redstone Transmitter: It can receive redstone signal from 4 inputs _(sides)_ and transmit to a receiver.
- Redstone Receiver: Receives the signal from a transmitter and distributes the value divided by the 4 outputs _(sides)_.
_(Receiving 10 Redstone Power and spreading it across 2 output would result in 5 Redstone Power on each output. Already receiving 10 Redstone Power and spreading it across 4 outputs would result in 2.5 rounded down, which would be 2 Redstone Power for each output.)_

The devices would operate across frequencies, for example:
A transmitter operating at frequency 100 would only send signal to receivers operating at frequency 100.
_(Ideally, the block would have the owner's ID, for example, UserID/100, so the Transmitter or Receiver would be in the UserID/100 frequency, but the user would just change the number, the ID would be automatic)
So everyone could use the same frequency but without interfering with each other._

And it could have a config.toml for the server that would define how far a signal from the transmitter could go.

There are some mods that do this, if you want some inspiration, I'll quote them.

1. [Ranged Wireless Redstone **(1.18)**](https://www.curseforge.com/minecraft/mc-mods/ranged-wireless-redstone)
2. [Redstone Gates **(1.18)**](https://www.curseforge.com/minecraft/mc-mods/redstone-gates)
3. [GIRC-Wireless-Redstone **(1.18)**](https://www.curseforge.com/minecraft/mc-mods/girc-wireless-redstone)
4. [Wireless Redstone CBE **(1.12)**](https://www.curseforge.com/minecraft/mc-mods/wireless-redstone-cbe)

I'm currently using Redstone Gates, as it has other interesting devices besides Transmitters and Receivers.
But particularly I think the Ranged Wireless Redstone's design is prettier.

But when you added the Logic Gate to your mod, the only thing holding me back from others is the transmitter haha
Its logic gate was innovative, it brings many possibilities in just 1 block, not limited to one type of gate per block (Like Redstone Gates)!

### Wireless Iron Door and Redstone Lamp

- A door and a lamp that also have activation frequencies.
So, by setting the same frequency as a transmitter, when the transmitter receives a redstone signal it opens the door or turns on the lamp.
- To set the frequency of the lamp, just right-click on it and the settings menu will appear.
- To set the frequency of the door, simply right-click on it while sneaking.
- Or there could be a device for configuring both.

**Comment by stfwi** [comment]
Hi fael, sorry man the mod is about to be feature complete :/. I also already have wireless in my Gauges and Switches mod, this mod here will  have a very tight scope window - only the few vanilla'rish blocks and one controller-like block. So, with a heavy heart, I have to say no.

**Comment by faelBrunnoS** [comment]
My friend, thank you very much for the reply!
I'm updating my server and I've already downloaded your Gauges mod!
I haven't tested it yet so I didn't know it had Wireless in it!
Good to know!
