### ISSUE TITLE
[Feature Request] Invisible Redstone Dust

### ISSUE THREAD

**Issue by faelBrunnoS** [stfwi/redstonepen#7]
### Invisible Redstone Dust
This idea would make your mod unique and with an exclusive option, at least I didn't find it anywhere.
- You would create an invisible redstone dust pen, when the dust is placed on the ground it just doesn't show up.
But when you wear special glasses, you would be able to see all the invisible dusts placed on the floor and walls.

It would be something like what you find in this mod: [SecretRoomsMod](https://www.curseforge.com/minecraft/mc-mods/secretroomsmod)

_This mod add some blocks that copy the texture of the block next to them, so these blocks are camouflaged and can have secret passages, secret chests, etc.
But if you wear special glasses, you can see which blocks are camouflaged._
![minecraft](https://user-images.githubusercontent.com/83606488/155200637-751f0b54-4fa4-4428-a420-010fe47ec8dd.gif)

In the case of redstone, instead of camouflaging itself, it would just not appear.
It would be as if the dust didn't have a texture, but when using the special glasses, the texture would appear highlighted so that the player could see which redstone dusts are invisible and which are not.
And you could fill the ceiling or wall of your house with redstone dust but no one would see them. (Unless he had the glasses.)

**Comment by stfwi** [comment]
Hi, definitely a cool idea. I need to think about it - the thing with Hidden Rooms is that something is shown, so people e.g. know that they cannot place something at the block location (where the walk-through-stone is in your screenshots). I have seen already quite a few problems however where blocks were that you could not see, e.g. placing did not work for no obvious reasons to the players. Or the hidden blocks were replaced and their functionalities were broken. Mostly these problematic blocks were invisible light emitting blocks, but I can imagine with invisible redstone the same problems could arise. Let's think again about the scenarios.

**Comment by faelBrunnoS** [comment]
I use Google Translate to translate the text, as I speak Portuguese!
But I think I understood some of what you said.

So, if that's what I understand, to get around this problem of not seeing where the invisible redstone powders are, I had this idea:

- Upon getting close enough to an Invisible Redstone Powder, it will emit a red particle. (Like the particle when Redstone is receiving a signal)
![redstone](https://user-images.githubusercontent.com/83606488/156850691-8d4aa4e0-e88c-41e6-be03-960fba0289b6.gif)

That way, the player would know when they have an Invisible Redstone Powder in front of them, so they wouldn't accidentally break the block.
And if the player has a Special Redstone Glasses, he would be able to see all the Invisible Redstone Dusts, even the ones that are far away from him.

I think that would solve most of the problem. (If that's what you said. As I said, I use Google Translate, and I answered based on what I understood.)

**Comment by stfwi** [comment]
Ok, thought about it now a few times - I think I like the mod to stay close to vanilla, means the dust should be visible. There are already quite a few mods out there providing wireless RS etc,  I guess these will be used in favour of invisible dust (it's a feature that would have to be maintained for all the coming MC versions, it's probably not used enough for that).
So, let's close this FR. Cheers,-
