### ISSUE TITLE
[Feature Request] Redstone Timer

### ISSUE THREAD

**Issue by faelBrunnoS** [stfwi/redstonepen#8]
### Redstone Timer
- A device that would have two operating modes:
- The first way you would set the activation time and the deactivation time, for example:

Adjustment Fields
Activation: 8000 ticks
Deactivation 10000 ticks

When the day reaches 8000 ticks the timer emits a redstone signal and then deactivates the signal only when the day reaches 10000 ticks.

- The second way could use the same fields but it would work like this:

Adjustment Fields
Activation: 8000 ticks
Deactivation 10000 ticks

The timer emits a redstone signal for 8000 ticks and after that time has passed, it is off for 10000 ticks and then on again for 8000 ticks and so on.
- On the device would have an option to switch between operating modes.

**Comment by stfwi** [comment]
Hi, here I can help ;) I added a Redstone Controller block (like a simplified PLC) that you can program freely. I also has timers (PLC timers TON, TOF, TP), which react depending on input signals, or also the `clock()` and `time()` functions. With `clock()` you can use the total game time in ticks as input, and with `time()` it's the day time from 0 to 24000 (0 is sunrise, 12000 sunset, 18000 midnight, etc). Have a look into the block, maybe that's exactly what you need ;)

**Comment by faelBrunnoS** [comment]
I understood!
I will review these settings!
Glad your Controller has such power!
I'll try to replicate what you said!
