### ISSUE TITLE
[Feature Request] Compatibility with Tiny Redstone

### ISSUE THREAD

**Issue by faelBrunnoS** [stfwi/redstonepen#9]
- Adding support for [Tiny Redstone](https://www.curseforge.com/minecraft/mc-mods/tiny-redstone) would be a really nice thing as it could use all your devices from the [Tiny Redstone](https://www.curseforge.com/minecraft/mc-mods/tiny-redstone) panel and create complex systems in just 1 block.
_(In this case, you would only need your devices, as the pen would not have functionality on the panels, as there is already tiny redstone dust.)_

The [Ranged Wireless Redstone](https://www.curseforge.com/minecraft/mc-mods/ranged-wireless-redstone) mod adds support, if you want to understand what I'm saying just install it and [Tiny Redstone](https://www.curseforge.com/minecraft/mc-mods/tiny-redstone)
_(The RWR mod only shows the Tiny Redstone devices if it is installed.)_

**Comment by stfwi** [comment]
Hi, for a one-block-control solution I added the RLC controller (okay, release date was late, but I was already a while on it).

RWR is also by Danny like Tiny Redstone is. He knows what he's doing for maintaining compat. I personally like how Redstone Pen and Tiny Redstone complement another - one for small scale, one for more-far-wiring. It fits really well already. So, in the not-too-tech-scope it's all covered I think. Also have a look at McJty's RFTools ecosystem for higher tech based packs. It's really really good.

**Comment by faelBrunnoS** [comment]
Alright, thanks for the reply!
